services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/macbook
      - POSTGRES_USER=macbook
      - POSTGRES_PASSWORD=macbook
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=macbook
      - POSTGRES_USER=macbook
      - POSTGRES_PASSWORD=macbook
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "macbook" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: